// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260927210000_AddSupplierSoftDelete")]
    public partial class AddSupplierSoftDelete
    {
    }
}
