// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Bolt.BoltIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("access_token");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_secret");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("company_name");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_connected");

                    b.Property<DateTime?>("LastFetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at_utc");

                    b.Property<DateTime?>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bolt_integrations");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_bolt_integrations_user_id");

                    b.ToTable("bolt_integrations", "public");
                });

            modelBuilder.Entity("Domain.Bolt.BoltOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("commission");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("destination_address");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("driver_name");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("driver_phone");

                    b.Property<string>("DriverUuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("driver_uuid");

                    b.Property<decimal>("NetEarnings")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_earnings");

                    b.Property<DateTime>("OrderCreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_created_time");

                    b.Property<DateTime?>("OrderFinishedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_finished_time");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("order_reference");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_status");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pickup_address");

                    b.Property<double>("RideDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("ride_distance");

                    b.Property<decimal>("RidePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ride_price");

                    b.Property<decimal>("Tip")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tip");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleLicensePlate")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vehicle_license_plate");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_model");

                    b.HasKey("Id")
                        .HasName("pk_bolt_orders");

                    b.HasIndex("UserId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("ix_bolt_orders_user_id_order_reference");

                    b.ToTable("bolt_orders", "public");
                });

            modelBuilder.Entity("Domain.Cars.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("approval_status");

                    b.Property<string>("Badges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("badges");

                    b.Property<string>("BoltCategories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bolt_categories");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("brand");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer")
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<bool>("DiscountActive")
                        .HasColumnType("boolean")
                        .HasColumnName("discount_active");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("engine");

                    b.Property<decimal?>("Garantie")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("garantie");

                    b.Property<string>("ListingSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("listing_source");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("location");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("offer_type");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("old_price");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_status");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by_user_id");

                    b.Property<decimal>("PricePerWeek")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_week");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_checkout_session_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("transmission");

                    b.Property<string>("UberCategories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("uber_categories");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_cars");

                    b.HasIndex("StripeCheckoutSessionId")
                        .HasDatabaseName("ix_cars_stripe_checkout_session_id");

                    b.HasIndex("StripeSubscriptionId")
                        .HasDatabaseName("ix_cars_stripe_subscription_id");

                    b.ToTable("cars", "public");
                });

            modelBuilder.Entity("Domain.Cars.CarImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_car_images");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_car_images_car_id");

                    b.ToTable("car_images", "public");
                });

            modelBuilder.Entity("Domain.Cars.CarLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("admin_note");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("car_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("InterestType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("interest_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_phone");

                    b.HasKey("Id")
                        .HasName("pk_car_leads");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_car_leads_car_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_car_leads_status");

                    b.ToTable("car_leads", "public");
                });

            modelBuilder.Entity("Domain.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_messages_chat_room_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_chat_messages_sender_id");

                    b.HasIndex("SentAtUtc")
                        .HasDatabaseName("ix_chat_messages_sent_at_utc");

                    b.ToTable("chat_messages", "public");
                });

            modelBuilder.Entity("Domain.Chat.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at_utc");

                    b.Property<Guid>("ProfessionalUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_rooms");

                    b.HasIndex("ProfessionalUserId")
                        .HasDatabaseName("ix_chat_rooms_professional_user_id");

                    b.HasIndex("ClientUserId", "ProfessionalUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_rooms_client_user_id_professional_user_id");

                    b.ToTable("chat_rooms", "public");
                });

            modelBuilder.Entity("Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("EncryptedFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("encrypted_file_path");

                    b.Property<string>("EncryptionIv")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("encryption_iv");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("PfaRegistrationId")
                        .HasDatabaseName("ix_documents_pfa_registration_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_documents_user_id");

                    b.ToTable("documents", "public");
                });

            modelBuilder.Entity("Domain.Expenses.DeductibleExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmountRon")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_ron");

                    b.Property<string>("CatalogCategory")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("catalog_category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DeductibleLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deductible_label");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_name");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_deductible_expenses");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_deductible_expenses_created_by_user_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_deductible_expenses_document_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_deductible_expenses_user_id");

                    b.HasIndex("PfaRegistrationId", "Year", "Month")
                        .HasDatabaseName("ix_deductible_expenses_pfa_registration_id_year_month");

                    b.ToTable("deductible_expenses", "public");
                });

            modelBuilder.Entity("Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("Domain.Payments.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountBani")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_bani");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_payment_id");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_records");

                    b.HasIndex("StripePaymentId")
                        .HasDatabaseName("ix_payment_records_stripe_payment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payment_records_user_id");

                    b.ToTable("payment_records", "public");
                });

            modelBuilder.Entity("Domain.Payments.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AmountBani")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_bani");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_phone");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_key");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_title");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_session_id");

                    b.HasKey("Id")
                        .HasName("pk_service_orders");

                    b.HasIndex("CustomerEmail")
                        .HasDatabaseName("ix_service_orders_customer_email");

                    b.HasIndex("StripeSessionId")
                        .HasDatabaseName("ix_service_orders_stripe_session_id");

                    b.ToTable("service_orders", "public");
                });

            modelBuilder.Entity("Domain.Payments.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("DashboardAccessGranted")
                        .HasColumnType("boolean")
                        .HasColumnName("dashboard_access_granted");

                    b.Property<DateTime?>("DashboardAccessGrantedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dashboard_access_granted_utc");

                    b.Property<DateTime>("FirstBillingDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_billing_date_utc");

                    b.Property<DateTime?>("NextBillingDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_billing_date_utc");

                    b.Property<int?>("PendingPlan")
                        .HasColumnType("integer")
                        .HasColumnName("pending_plan");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_subscriptions");

                    b.HasIndex("StripeCustomerId")
                        .HasDatabaseName("ix_user_subscriptions_stripe_customer_id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_subscriptions_stripe_subscription_id")
                        .HasFilter("stripe_subscription_id IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_subscriptions_user_id");

                    b.ToTable("user_subscriptions", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.HasKey("Id")
                        .HasName("pk_pfa_activity_logs");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("ix_pfa_activity_logs_performed_by_user_id");

                    b.HasIndex("PfaRegistrationId")
                        .HasDatabaseName("ix_pfa_activity_logs_pfa_registration_id");

                    b.ToTable("pfa_activity_logs", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaFiscalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountingRegime")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("accounting_regime");

                    b.Property<string>("BoltStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bolt_status");

                    b.Property<string>("CashRegisterStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cash_register_status");

                    b.Property<string>("CashRevenueStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cash_revenue_status");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("HasEmployees")
                        .HasColumnType("boolean")
                        .HasColumnName("has_employees");

                    b.Property<bool>("IsVatPayer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vat_payer");

                    b.Property<string>("OtherPlatformsStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("other_platforms_status");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<Guid?>("SpecialVatCodeDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_vat_code_document_id");

                    b.Property<DateTime?>("SpecialVatCodeObtainedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("special_vat_code_obtained_at_utc");

                    b.Property<string>("SpecialVatCodeStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("special_vat_code_status");

                    b.Property<string>("TaxationSystem")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("taxation_system");

                    b.Property<string>("UberStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("uber_status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid?>("VehicleSupportingDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_supporting_document_id");

                    b.Property<string>("VehicleSupportingDocumentLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("vehicle_supporting_document_label");

                    b.Property<string>("VehicleUsageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vehicle_usage_type");

                    b.HasKey("Id")
                        .HasName("pk_pfa_fiscal_profiles");

                    b.HasIndex("PfaRegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_pfa_fiscal_profiles_pfa_registration_id");

                    b.HasIndex("SpecialVatCodeDocumentId")
                        .HasDatabaseName("ix_pfa_fiscal_profiles_special_vat_code_document_id");

                    b.HasIndex("VehicleSupportingDocumentId")
                        .HasDatabaseName("ix_pfa_fiscal_profiles_vehicle_supporting_document_id");

                    b.ToTable("pfa_fiscal_profiles", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaFleetConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<bool>("BoltApiAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("bolt_api_accepted");

                    b.Property<DateTime?>("BoltApiAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bolt_api_accepted_at_utc");

                    b.Property<string>("ConsentTextVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("consent_text_version");

                    b.Property<bool>("FleetAccountsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("fleet_accounts_accepted");

                    b.Property<DateTime?>("FleetAccountsAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fleet_accounts_accepted_at_utc");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.HasKey("Id")
                        .HasName("pk_pfa_fleet_consents");

                    b.HasIndex("PfaRegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_pfa_fleet_consents_pfa_registration_id");

                    b.ToTable("pfa_fleet_consents", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaInternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_pfa_internal_notes");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_pfa_internal_notes_created_by_user_id");

                    b.HasIndex("PfaRegistrationId")
                        .HasDatabaseName("ix_pfa_internal_notes_pfa_registration_id");

                    b.ToTable("pfa_internal_notes", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaMonthlyIncome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_processed");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("processed_by_user_id");

                    b.Property<decimal>("TaxeEstimate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("taxe_estimate");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<decimal>("VenitBolt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("venit_bolt");

                    b.Property<decimal>("VenitCard")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("venit_card");

                    b.Property<decimal>("VenitCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("venit_cash");

                    b.Property<decimal>("VenitUber")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("venit_uber");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_pfa_monthly_incomes");

                    b.HasIndex("ProcessedByUserId")
                        .HasDatabaseName("ix_pfa_monthly_incomes_processed_by_user_id");

                    b.HasIndex("PfaRegistrationId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_pfa_monthly_incomes_pfa_registration_id_year_month");

                    b.ToTable("pfa_monthly_incomes", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaPlatformAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfiguredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("configured_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("PasswordProtected")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_protected");

                    b.Property<DateTime?>("PasswordUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_updated_at_utc");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_pfa_platform_accounts");

                    b.HasIndex("PfaRegistrationId", "Provider", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_pfa_platform_accounts_pfa_registration_id_provider_kind");

                    b.ToTable("pfa_platform_accounts", "public");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedContabilId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_contabil_id");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<int?>("ContractDuration")
                        .HasColumnType("integer")
                        .HasColumnName("contract_duration");

                    b.Property<string>("County")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Cui")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cui");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("registration_type");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("street");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pfa_registrations");

                    b.HasIndex("AssignedContabilId")
                        .HasDatabaseName("ix_pfa_registrations_assigned_contabil_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_pfa_registrations_reviewed_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pfa_registrations_user_id");

                    b.ToTable("pfa_registrations", "public");
                });

            modelBuilder.Entity("Domain.Uber.UberCsvImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashCollected")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cash_collected");

                    b.Property<decimal>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("file_type");

                    b.Property<decimal>("GrossEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_earnings");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<double>("Kilometers")
                        .HasColumnType("double precision")
                        .HasColumnName("kilometers");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<decimal>("NetEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_earnings");

                    b.Property<double>("OnlineHours")
                        .HasColumnType("double precision")
                        .HasColumnName("online_hours");

                    b.Property<Guid>("PfaRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pfa_registration_id");

                    b.Property<double>("RideHours")
                        .HasColumnType("double precision")
                        .HasColumnName("ride_hours");

                    b.Property<int>("Trips")
                        .HasColumnType("integer")
                        .HasColumnName("trips");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_uber_csv_imports");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_uber_csv_imports_user_id");

                    b.HasIndex("PfaRegistrationId", "Year", "Month")
                        .HasDatabaseName("ix_uber_csv_imports_pfa_registration_id_year_month");

                    b.HasIndex("PfaRegistrationId", "Year", "Month", "FileType", "FileName")
                        .IsUnique()
                        .HasDatabaseName("ix_uber_csv_imports_pfa_registration_id_year_month_file_type_f");

                    b.ToTable("uber_csv_imports", "public");
                });

            modelBuilder.Entity("Domain.Users.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Bolt.BoltIntegration", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bolt_integrations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Bolt.BoltOrder", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bolt_orders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Cars.CarImage", b =>
                {
                    b.HasOne("Domain.Cars.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_images_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Domain.Cars.CarLead", b =>
                {
                    b.HasOne("Domain.Cars.Car", "Car")
                        .WithMany("Leads")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_leads_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Domain.Chat.ChatMessage", b =>
                {
                    b.HasOne("Domain.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_rooms_chat_room_id");

                    b.HasOne("Domain.Users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_users_sender_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Chat.ChatRoom", b =>
                {
                    b.HasOne("Domain.Users.User", "ClientUser")
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_rooms_users_client_user_id");

                    b.HasOne("Domain.Users.User", "ProfessionalUser")
                        .WithMany()
                        .HasForeignKey("ProfessionalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_rooms_users_professional_user_id");

                    b.Navigation("ClientUser");

                    b.Navigation("ProfessionalUser");
                });

            modelBuilder.Entity("Domain.Documents.Document", b =>
                {
                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", null)
                        .WithMany("Documents")
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documents_pfa_registrations_pfa_registration_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Expenses.DeductibleExpense", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deductible_expenses_users_created_by_user_id");

                    b.HasOne("Domain.Documents.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deductible_expenses_documents_document_id");

                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithMany()
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deductible_expenses_pfa_registrations_pfa_registration_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deductible_expenses_users_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");

                    b.Navigation("PfaRegistration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Payments.PaymentRecord", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_records_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Payments.UserSubscription", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaActivityLog", b =>
                {
                    b.HasOne("Domain.Users.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_activity_logs_users_performed_by_user_id");

                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithMany()
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_activity_logs_pfa_registrations_pfa_registration_id");

                    b.Navigation("PerformedByUser");

                    b.Navigation("PfaRegistration");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaFiscalProfile", b =>
                {
                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithOne("FiscalProfile")
                        .HasForeignKey("Domain.PfaRegistrations.PfaFiscalProfile", "PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_fiscal_profiles_pfa_registrations_pfa_registration_id");

                    b.HasOne("Domain.Documents.Document", "SpecialVatCodeDocument")
                        .WithMany()
                        .HasForeignKey("SpecialVatCodeDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pfa_fiscal_profiles_documents_special_vat_code_document_id");

                    b.HasOne("Domain.Documents.Document", "VehicleSupportingDocument")
                        .WithMany()
                        .HasForeignKey("VehicleSupportingDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pfa_fiscal_profiles_documents_vehicle_supporting_document_id");

                    b.Navigation("PfaRegistration");

                    b.Navigation("SpecialVatCodeDocument");

                    b.Navigation("VehicleSupportingDocument");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaFleetConsent", b =>
                {
                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithOne("FleetConsent")
                        .HasForeignKey("Domain.PfaRegistrations.PfaFleetConsent", "PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_fleet_consents_pfa_registrations_pfa_registration_id");

                    b.Navigation("PfaRegistration");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaInternalNote", b =>
                {
                    b.HasOne("Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_internal_notes_users_created_by_user_id");

                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithMany()
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_internal_notes_pfa_registrations_pfa_registration_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PfaRegistration");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaMonthlyIncome", b =>
                {
                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithMany()
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_monthly_incomes_pfa_registrations_pfa_registration_id");

                    b.HasOne("Domain.Users.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pfa_monthly_incomes_users_processed_by_user_id");

                    b.Navigation("PfaRegistration");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaPlatformAccount", b =>
                {
                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithMany("PlatformAccounts")
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_platform_accounts_pfa_registrations_pfa_registration_id");

                    b.Navigation("PfaRegistration");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaRegistration", b =>
                {
                    b.HasOne("Domain.Users.User", "AssignedContabil")
                        .WithMany()
                        .HasForeignKey("AssignedContabilId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pfa_registrations_users_assigned_contabil_id");

                    b.HasOne("Domain.Users.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .HasConstraintName("fk_pfa_registrations_users_reviewed_by_user_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pfa_registrations_users_user_id");

                    b.Navigation("AssignedContabil");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Uber.UberCsvImport", b =>
                {
                    b.HasOne("Domain.PfaRegistrations.PfaRegistration", "PfaRegistration")
                        .WithMany()
                        .HasForeignKey("PfaRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uber_csv_imports_pfa_registrations_pfa_registration_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uber_csv_imports_users_user_id");

                    b.Navigation("PfaRegistration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Users.PushSubscription", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Cars.Car", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("Domain.Chat.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.PfaRegistrations.PfaRegistration", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("FiscalProfile");

                    b.Navigation("FleetConsent");

                    b.Navigation("PlatformAccounts");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("PushSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
